### ISSUE TITLE
--range does not prevent negative values if the record is not first in file

### ISSUE THREAD

**Issue by tzintzuni** [bedops/bedops#142]
Hi, 

I'm running bedops 2.4.12 -- just updated today to make sure this behavior was still there.

I have two bed files for illustration:
```
> cat 1rec.bed
chrUn_gl000226	158	159	peak_17	0	.
> cat 2rec.bed 
chrUn_gl000226	10025	10026	peak_16	0	.
chrUn_gl000226	158	159	peak_17	0	.
```

I'm trying to expand the ranges by 250bp in both directions. In the case of peak_17 this will move the start below 0. According to the documentation, the region should grow asymmetrically to prevent this, and if I use a bed file with only that peak it works fine:
```
> bedops --everything --range 250 1rec.bed
chrUn_gl000226	0	409	peak_17	0	.
```
But if I use a bed file where  another record is encountered first I get a negative value:
```
bedops --everything --range 250 2rec.bed
chrUn_gl000226	9775	10276	peak_16	0	.
chrUn_gl000226	18446744073709551524	409	peak_17	0	.

```

It seems the expected behavior only works in the first line:
```
> cat 3rec.bed 
chrUn_gl000226	158	159	peak_17	0	.
chrUn_gl000226	10025	10026	peak_16	0	.
chrUn_gl000226	158	159	peak_17	0	.
> bedops --everything --range 250 3rec.bed
chrUn_gl000226	0	409	peak_17	0	.
chrUn_gl000226	9775	10276	peak_16	0	.
chrUn_gl000226	18446744073709551524	409	peak_17	0	.
```

**Comment by sjneph** [comment]
Thanks for the report.  The issue seems to be that your input file is not sorted properly.  Consider:
```
> cat ok.bed
chrUn_gl000226  158 159 peak_17 0   .
chrUn_gl000226  170 175 peak_18 0
chrUn_gl000226  10025   10026   peak_16 0   .
> bedops --everything --range 200 ok.bed
chrUn_gl000226  0   359 peak_17 0   .
chrUn_gl000226  0   375 peak_18 0
chrUn_gl000226  9825    10226   peak_16 0   . 
```

the program correctly re-organizes records to maintain sorted order in the event that truncation at base 0 collides with a fully nested element.  Consider:
```
> cat ok2.bed
chrUn_gl000226  158 209 peak_17 0   .
chrUn_gl000226  170 175 peak_18 0
chrUn_gl000226  10025   10026   peak_16 0   .
> bedops --everything --range 200 ok2.bed
chrUn_gl000226  0   375 peak_18 0
chrUn_gl000226  0   409 peak_17 0   .
chrUn_gl000226  9825    10226   peak_16 0   . 
```

I also verified that your input file works as expected when it's properly sorted.  Use the sort-bed program to sort your file one time.  After that, results from bedops are guaranteed to also be in sorted order, so you can use them immediately as inputs to bedops and other utilities in the suite.  I'm closing this out - if you find a counterexample to my claims, please feel free to re-open.  Thanks for using BEDOPS!
