### ISSUE TITLE
Bug: bedmap produces NaNs

### ISSUE THREAD

**Issue by mdozmorov** [bedops/bedops#149]
Annotating one BED file by scores from another using bedmap (v2.4.2) generates NaNs. The same using intersectBed works as expected. Reproducible example below, and there are numerous other such cases.

$ bedmap --max tmp.bed tmp3.bed
0.422050
0.422050
0.844230
0.000000
NAN

$ intersectBed -loj -wa -a tmp.bed -b tmp3.bed | cut -f8
0.42205
0.42205
0.84423
0
1.59736

tmp.bed and tmp3.bed (127Mb) can be provided

**Comment by sjneph** [comment]
Note that bedmap is currently at version 2.4.14.  Could you update your program and try again?  We are happy to look at it, but do please provide an example set of inputs.

**Comment by mdozmorov** [comment]
To reproduce:
https://www.dropbox.com/s/3j0rl897xlpui4u/tmp.bed?dl=0
https://www.dropbox.com/s/4aq4igv918gq255/tmp3.bed.gz?dl=0

Same thing with 2.4.14 version. Previous installation (on Mac) was through 'brew install'.

$ bedmap --version
bedmap
  citation: http://bioinformatics.oxfordjournals.org/content/28/14/1919.abstract
  version:  2.4.14
  authors:  Shane Neph & Scott Kuehn

$ bedmap --max tmp.bed tmp3.bed
0.422050
0.422050
0.844230
0.000000
NAN

$ intersectBed -loj -wa -a tmp.bed -b tmp3.bed | cut -f8
0.42205
0.42205
0.84423
0
1.59736

**Comment by sjneph** [comment]
bedmap --ec --max tmp.bed tmp3.bed
indicates that tmp.bed is not properly sorted.

sort-bed tmp.bed
shows that line 6 has a tab too.  You should remove that, then:

sort-bed tmp.bed | bedmap --ec --max - tmp3.bed
will work fine for you.

BEDOPS tools have 1 main requirement - that all inputs are sorted per the sort-bed utility.  That is a 1-time overhead that makes all downstream calculations efficient in time and memory.  Tools (bedops/bedmap/closest-features) produce sorted outputs (though --echo needs to be used with bedmap) so that you can pipe things along without any further overhead due to sorting the data.  It looks like tmp3.bed is properly sorted.

Feel free to re-open this if you have any further comments or concerns.

**Comment by mdozmorov** [comment]
Works fine. Yes, saw the requirement. Apparently, previous steps, supposedly sorting the data, didn't work as expected. Thanks!
