### ISSUE TITLE
bedmap output with 0

### ISSUE THREAD

**Issue by tianfree** [bedops/bedops#153]
I compared the output of bedmap (version:  2.4.16) with map.bed and map.bed.starch:
`bedmap reference.bed map.bed.starch`
Output:

> 1 0 10000
> 1 10000 7047
> 1 20000 0
> 1 30000 0
> 1 40000 0
> 1 50000 0
> 1 60000 0
> 1 70000 0
> 1 80000 0
> 1 90000 0

`bedmap reference.bed map.bed`
Output:

> 1 0 10000
> 1 10000 8945
> 1 20000 10000
> 1 30000 10000
> 1 40000 9951
> 1 50000 9973
> 1 60000 10000
> 1 70000 9978
> 1 80000 9970
> 1 90000 9976

The only difference is the map file (before or after become starch)
But in bedmap (version:  2.4.15) it is normal.
Is there some trick in bemap ?

**Comment by bedops** [comment]
Hi Feng,
It looks like you simplified out the options. What options are you using.
Could you add ---ec and see if bedmap complains?  If you can attach the
files, I can look in more detail.
Shane
On Apr 14, 2016 7:42 PM, "Feng Tian" <notifications@github.com> wrote:

I compared the output of bedmap (version: 2.4.16) with map.bed and
map.bed.starch:
bedmap reference.bed map.bed.starch
Output:

1 0 10000
1 10000 7047
1 20000 0
1 30000 0
1 40000 0
1 50000 0
1 60000 0
1 70000 0
1 80000 0
1 90000 0

bedmap reference.bed map.bed
Output:

1 0 10000
1 10000 8945
1 20000 10000
1 30000 10000
1 40000 9951
1 50000 9973
1 60000 10000
1 70000 9978
1 80000 9970
1 90000 9976

The only difference is the map file (before or after become starch)
Is there some trick in bemap ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/bedops/bedops/issues/153>

**Comment by tianfree** [comment]
My command is:
`bedmap --ec --delim "\t" --prec 0 --bp-ovr 1 --echo --bases $ref $umap`
It is in the "run_10kb_counts.tok" of hotspot v4.1.0.
I just extracted this command from it.

Now I am using bedops v 2.4.15 with the same options and the output is normal.

**Comment by bedops** [comment]
So you are using run_10kb_counts.tok for both of your $ref and $umap?

**Comment by tianfree** [comment]
Yes.
`./run_10kb_counts.tok`
without any option because the file was directly generated by hotspot.

**Comment by alexpreynolds** [comment]
Provisional fixes are in commit 66437c70a042fa93f02b7734d8190a3622e0fd1e
