### ISSUE TITLE
GTF to bed chromosome coordination change

### ISSUE THREAD

**Issue by xinl22** [bedops/bedops#204]
When I use gtf2bed I found the start position will -1 after conversion. But why end position remain the same?

**Comment by sjneph** [comment]
GFF uses inclusive coordinate range, meaning:
chr1  1   10
is 10 bp long.  BED is defined using a [start, end) so that the end coordinate is 1 bp beyond the range represented.  So that same line is only 9 bp long in BED (notice that 10-1 = 9).  The gff2bed tool converts the GFF coordinates given into appropriate BED coordinates.
You can adjust things yourself once you have a BED file as you see fit:
`bedops -u --range 1:0 file.bed`
would add +1 to start coordinates and 0 to the end coordinates found in file.bed.

**Comment by alexpreynolds** [comment]
Also see the documentation: http://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/gtf2bed.html

> The `gtf2bed` script converts 1-based, closed `[start, end]` Gene Transfer Format v2.2 (GTF2.2) to sorted, 0-based, half-open `[start-1, end)` extended BED-formatted data.

Conversion from 1- to 0-based indexing is done for the sake of convenience. Most BED files have a 0-based index when used in set operations.

**Comment by alexpreynolds** [comment]
I'll close this up, since there isn't much more about this to discuss. Feel free to comment or follow up if you have more questions!
