### ISSUE TITLE
Error: Invalid wig ID on line 1

### ISSUE THREAD

**Issue by ghost** [bedops/bedops#239]
Hello, trying 

```
wig2bed < asm.dist_5_kad.wig
Error: Invalid wig ID on line 1
```
here is the beginning of my wig file

```
variableStep  chrom=Chrom_1
1	1.661
2	1.649
3	1.645
4	1.644
5	1.6434
6	1.64233333333333
7	1.64128571428571
8	1.6405
9	1.63988888888889
```
it seems all right to me. 
Thanks

**Comment by aderzelle** [comment]
Got it, it needs the multisplit tag 
The error message is a bit misleading though.

**Comment by alexpreynolds** [comment]
Thanks for the report. 

Because this input is a file stream, and not a regular file, there would be no way for wig2bed (convert2bed) to read ahead and know that the input contains multiple sections, without reading through the entire file. 

But I'll look at modifying the error message to suggest to the user to investigate if the wig file contains multiple sections, in the case this error is thrown.

**Comment by aderzelle** [comment]
Ah ok I understand. But yes if it threw a line saying "maybe there are multiple sections" that would be handy.

thank you for bedops

**Comment by alexpreynolds** [comment]
Yep, that's probably what I'll do. I'll leave this ticket open to add a commit.

**Comment by izabelcavassim** [comment]
Came here with the same problem and above. Maybe it would be nice to output the --multisplit to the user. 
This is how to fix anyway:
convert2bed --input=wig --multisplit --output=bed < input.wig > output.bed

or: 
wig2bed --multisplit < input.wig > output.bed

Thank you both!

**Comment by alexpreynolds** [comment]
Fixed in https://github.com/bedops/bedops/commit/d9776fdd215e8264b689081c4c7c98482f02b3e2

**Comment by rsharris** [comment]
I ran into this problem today, same error, apparently the same cause, running version 2.4.39 (installed via conda). I also tried to test by building an executable from the repo, but wasn't able to successfully run convert2bed-typical --input=wig (because the "sort-bed binary" apparently isn't installed on this machine).

I was following the instructions from a tool/pipeline from someone's ≈4 year old paper. So either this behavior didn't exist then, or that author didn't accurately relate the commands in his pipeline.

Indeed, adding the command-line option --multisplit=something fixes the problem (or, I should say, the problem doesn't occur on line 1). But I'm at a loss as to how I (or any other user) could be expected to discover this. The error message makes you think the input wig file is non-compliant. So I kept looking at the UCSC wiggle format spec and at my file and damned if it didn't look fine.

And I pored through the options to see if there was something I was missing. And now even that I know --multisplit is the answer, and reading the description of that option, I would never have realized that is the magic incantation needed to solve my problem.

As best I can tell, this error comes from line ≈6110 in convert2bed.c. And it doesn't look to me like it is checking the validity of a wig ID. It's just checking whether the internal wig->id string is empty. And that string is empty because wig->start_write is initialized as false and never gets set to true.

A more useful error mesage would include the suggestion that user try "--multisplit".

**Comment by alexpreynolds** [comment]
@rsharris Thanks for the report. Streaming input is great because it is fast. It can be problematic, however, as there is no way to check if the input is valid, or that certain options are required, until after chunks of data come in. If you can provide a link to the input or paper, I can investigate that file and see if a patch makes sense. Let me know if I can help further.

**Comment by alexpreynolds** [comment]
Added warning message in commit d932dc1e

**Comment by rsharris** [comment]
Cool. I'm a big proponent of trying to make the program tell the user what might solve the problem. If for no other reason than that it might cut down on users having to resort to contacting me.
