### ISSUE TITLE
Makefiles do not respect users CXXFLAGS

### ISSUE THREAD

**Issue by mmokrejs** [bedops/bedops#242]
Hi,
  I would like to you to point you to this patch from Gentoo Linux for a bit older bedops version but you will get the idea what are the needed changes. It is a pitty user's environmet settings, namely the compile flags, are ignored and replaced by some hardcoded defaults.

[bedops-2.4.26-respect-cxxflags.patch.txt](https://github.com/bedops/bedops/files/5308520/bedops-2.4.26-respect-cxxflags.patch.txt)

**Comment by alexpreynolds** [comment]
If I can apply these changes and preserve the ability to compile per our existing procedure, then I will do so for the next release version. If this patch does not work with a stock build process, then I may need to revert back to the current compile flags.

**Comment by mmokrejs** [comment]
It just respects users CXXFLAGS, otherwise enforces -O3 as before. It allows to compile for many other arches.

Ideally, also users CXX, CC and CFLAGS should be respected, in your Makefile code. Thank you.

**Comment by alexpreynolds** [comment]
Modified makefiles for Darwin target in commit `52a2d650`

**Comment by alexpreynolds** [comment]
Modified makefiles for Linux target in commit 4bb5ab0. For both Linux and Darwin targets, you should be able to specify `CXXFLAGS` and `CFLAGS` variables. 

I'm going to close this issue. Some optimization flags may be overridden downstream, however. If that presents an issue for a specific OS, feel free to follow up. In that case, it would be helpful to have more detail about the OS and relevant flags in order to modify these makefiles and to do further build testing. Thanks.
