### ISSUE TITLE
Should bedops sort-bed really fail if the start and end position are the same?

### ISSUE THREAD

**Issue by alexlenail** [bedops/bedops#258]
I have a [bed-like file](https://www.meuleman.org/research/dhsindex/) with identical start/stop coordinates. When I try to `sort-bed` I get
```
Genomic end coordinate is less than (or equal to) start coordinate.
```

It's true, this file contains zero-length regions. But it should still be possible to sort, right? If it's still possible to induce an ordering on genomic regions with zero length, couldn't this just be a warning rather than an error?

(I see a variant of this question was asked in #245)

**Comment by alexpreynolds** [comment]
BED input is typically defined to contain zero-indexed, half-open intervals over the set of positive integers. The `sort-bed` tool is written to make sure that kind of input goes through the other tools in this kit.

A half-open interval leaves out the end position. For example `[100, 101)` is the set of integers greater than or equal to 100 and less than 101. For the purposes of genomic operations, `[100, 101)` represents position 100 on some (unnamed) chromosome.

A half-open interval like `[100, 100)` doesn't contain position 100. This describes an interval greater than or equal to 100, and also less than 100. No such integer exists. This is the empty set (∅). An empty set doesn't represent a position on a chromosome, assuming we use BED indexing.

Operations on an empty set, like intersections, subsets, mapping etc. give an empty set as output. For example, a correctly-defined position 100 will map to or associate with an interval containing positions 100 and 101, because the two intervals overlap:

```
% bedmap --echo --echo-map <(echo -e 'chr1\t100\t101') <(echo -e 'chr1\t100\t102')
chr1	100	101|chr1	100	102
```

But the empty set does not (cannot) overlap, so no answer is given:

```
% bedmap --echo --echo-map <(echo -e 'chr1\t100\t100') <(echo -e 'chr1\t100\t102')
chr1	100	100|
```

For purposes of avoiding these and similar problems with set and map operations, this kit sticks to handling non-empty intervals and treats the latter as an error case to be fixed, e.g., by way of `sort-bed` or by using `--ec` to do error checking:

```
% bedmap --ec --echo --echo-map <(echo -e 'chr1\t100\t100') <(echo -e 'chr1\t100\t102')
May use bedmap --help for more help.

Error: in /dev/fd/11
End coordinates must be greater than start coordinates.
See row: 1
```

Perhaps you're working with SNPs or SNVs. If your coordinates are one-indexed, fully-closed, then you can convert them to zero-indexed, half-open data by subtracting one from the start position, followed by piping to `sort-bed`, e.g.:

    $ awk -v FS="\t" -v OFS="\t" '(($2 != 0) && ($2==$3)){ $2--; print $0; }' oneIndexedFullyClosed.txt | sort-bed - > zeroIndexedHalfOpen.bed

Whether you use `sort-bed` or other sort approaches, the important thing is to avoid empty-set intervals when doing downstream set or map operations.

**Comment by alexpreynolds** [comment]
There's a useful overview on Biostars of the differences in index schemes commonly found in different genomics formats, how they are used to represent elements, and how to translate between schemes: https://www.biostars.org/p/84686/
