### ISSUE TITLE
Document performance of `bedextract`

### ISSUE THREAD

**Issue by alexlenail** [bedops/bedops#266]
I'm curious about the relative performances of 
- `bedextract` for starched bed files 
- `tabix` for gzipped bed files 
- `pyBigWig` for bigBed files

for extracting records in bed-like files overlapping some set of query intervals. Which will be most performant?

**Comment by alexpreynolds** [comment]
Performance could be determined by either query speed or storage
efficiency.

Query speed is a little complicated.

Tabix and bigBed extraction will almost certainly run ad-hoc interval
queries faster than unstarch (or unstarch routines in bedextract, bedops,
bedmap, etc.). However, Starch is the most efficient compression format of
the three.

As one example, a four-column bedGraph will be compressed to 30% of its
original size in gzip, but to 4% in Starch. For a large-scale sequencing
facility like the one I work at, that could add up to significant savings
in storage needs.

I don't have the numbers for bigBed, but I imagine it should be worse than
gzip, because it stores the original data at different levels.

One advantage of Starch is that you can run interval operations directly on
Starch files with bedops/bedmap/etc., whereas you must typically first
extract data from gzip or bigBed to text, before doing set operations with
BEDOPS or other tools.

Of course, you can use process substitutions to mix and match, e.g.:

```
bedmap --echo --echo-map <(gunzip -c foo.bed.bgz) bar.bed.starch
```

You can also use `--chrom <chrom>` with bedops and bedmap to focus
operations on one chromosome:

```
bedmap --chrom chrN --echo --echo-map <(tabix chrN foo.bed.bgz)
bar.bed.starch
```

This is very useful for splitting up work on a cluster by chromosome, and
BEDOPS comes with a couple helper scripts that use this property for
quickly making Starch files.

Further, with bedmap and bedextract, if your inputs are not nested, you can
add `--faster` to take advantage of that property to improve set operation
efficiency. It can be combined with `--chrom` for further time savings:

```
bedmap --faster --chrom chrN --echo --echo-map <(tabix chrN foo.bed.bgz)
bar.bed.starch
```

Ref.
https://bedops.readthedocs.io/en/latest/content/reference/set-operations/nested-elements.html#why-nested-elements-matter

You can also pipe results from process to process with BEDOPS tools, which
isn't possible with UCSC bigBed tools, and might not be easily possible
with bedtools (at least not until recently?).

Anyway, the answer is complicated because most production use of set ops
tools are generally part of larger, complex pipelines, and there are
"tricks" that can improve performance considerably, even without
tabix/bigBed.

**Comment by alexlenail** [comment]
Thanks for this thorough reply. 

It sounds like if my use case is just getting the records overlapping some regions (for plotting downstream), I should choose between querying bigBed with pyBigWig and gzipped bed files with tabix. I'm quite curious which will be faster for many small regions, for a very large (gzipped / big)bed file..

**Comment by alexpreynolds** [comment]
If you're trying to summarize and plot signal over a set of regions, you might look at the deepTools kit.

Generally, if you have many thousands of small regions, it might be worth looking at ways to window and merge them into one or more larger contiguous intervals. 

Asking for larger chunks of data from one (or a few) larger queries will usually be faster than many smaller queries, which require file operations that hit the index, and seek into the archive over and over again. 

The result will be larger than you need, but it can be filtered in memory with (faster) set operations over your true list of small regions.

**Comment by alexlenail** [comment]
Ah that's interesting -- I would not have guessed that windowing/merging could be faster. You've clearly guessed my use case: I have a >200GB bed file of TF binding sites, and a bed file of 20k ATAC-seq peaks. How would you recommend subsetting the TFBS file to the regions overlapping the ATAC peaks most efficiently on a cluster? I'd like this code to be as fast as possible, since I anticipate I'll be calling it regularly.

**Comment by alexpreynolds** [comment]
I didn't know this before, but `tabix` has an option (`-R`) to read in a BED file of **1-based** query regions, so that's probably a good way to do things, to start.

The first step I'd take is to split up work onto separate cluster nodes by chromosome. E.g., for Slurm:

```
#!/bin/bash

mkdir -p ${PWD}/results
for chr in `seq 1 22` X Y
do
    chrom="chr${chr}"
    sbatch --export=ALL,chrom=${chrom},dest=${PWD}/results ${PWD}/subset.sh 
done
```

The `subset.sh` script might look like:

```
#!/bin/bash
#SBATCH /* whatever cluster options are useful, e.g. output and error log files, memory, CPU, etc. */

tabix -p bed -R ${TFBS} ${ATAC_seq_peaks} > ${dest}/${chrom}.bed
```

`${TFBS}` should be an indexed bgzip-compressed BED file. 

`${ATAC_seq_peaks}` should be a compressed or uncompressed BED file containing **1-based indexed regions** (unusual for BED, but that's what it asks for).

If this is too slow, I'd look at windowing each peak, merging the windows, querying those windowed-merged peaks with `tabix`, then post-filtering the resulting TFBS hits with `bedops` or similar against the original (non-windowed) peaks. Something like:

```
#!/bin/bash
#SBATCH /* whatever cluster options are useful, e.g. output and error log files, memory, CPU, etc. */

bedops --range ${window} --everything ${ATAC_seq_peaks} | bedops --merge - > .tmp
tabix -p bed -R ${TFBS} .tmp | bedops -e 1 - ${ATAC_seq_peaks} > ${dest}/${chrom}.bed
rm -f .tmp
```

The `${window}` value should be large enough to span two or more peaks on average. You'd want to explore this on a small subset to tune this to get the most bang for the buck on the cost of `tabix` queries. It might be sufficient to use `-R` directly, however, and for simplicity I'd start there with a chromosome or two (maybe `chr22` or `chrY`, something small).

Hope this helps!

**Comment by alexpreynolds** [comment]
Just a note that I updated my answer, so it might help to look at this page on the Github site.
