### ISSUE TITLE
*** Error in `convert2bed': realloc(): invalid next size: 0x00005639369afba0 ***

### ISSUE THREAD

**Issue by aalkin2001** [bedops/bedops#274]
Hi,

I am having issue converting hg38.refGene.gtf from UCSC genome browser to bed file format. Please see the attached screenshot of error messages and how do I solve this issue.

Thank you.

![gtf2bed_file1](https://user-images.githubusercontent.com/30750268/204655212-2c09391b-8acb-4734-992c-c29297f9866f.png)
![gtf2bed_file2](https://user-images.githubusercontent.com/30750268/204655214-3ae4a8fc-f824-49b8-addf-f97061764e96.png)

**Comment by alexpreynolds** [comment]
Instead of using `conda` to install BEDOPS, please use one of the other installation methods outlined here (presuming Ubuntu, based on screenshot), such as the precompiled binaries available via Github:

https://bedops.readthedocs.io/en/latest/content/installation.html#linux

For whatever reason, the version that is distributed via bioconda can sometimes have issues. I don't have a good way to troubleshoot bioconda/anaconda/conda issues without a reproducible setup, unfortunately, but the precompiled binaries I make should work with any version of Linux within the last several years.

When using `gtf2bed` with `--max-mem`, you want to add `--sort-tmpdir` and specify those two options with `gtf2bed`, e.g.:

```
gtf2bed --max-mem 2G --sort-tmpdir=/path/to/some/directory < annotations.gtf > annotations.bed
```

Please remember to change `/path/to/some/directory` to another directory on your host that has 2G of usable disk space. 

I'm going to close this up, but if you're still having problems, please post a **text-based** error message (no screenshots) and include some details about your host and environment, which will help me help you with troubleshooting.
